"use client";
// File: components/ai/DraftCard.tsx
// One AI draft (NPC / Loot / Quest / Recap) — preview, edit, reject, approve.
// Presentational + local state only; all mutations bubble up via callbacks.
// Inherits DESIGN_SYSTEM tokens (no new colors). Color-not-only: every action has a label.

import { useState } from "react";
import { ChevronDown, ChevronUp, Check, Eye, EyeOff } from "lucide-react";
import type { AIDraftView, AIDraftEntityType } from "@/lib/ai/types";

const ENTITY_META: Record<AIDraftEntityType, { label: string; cls: string }> = {
  npc: { label: "NPC", cls: "text-arcane border-arcane/40" },
  loot: { label: "Loot", cls: "text-accent border-accent/40" },
  quest: { label: "Quest", cls: "text-muted border-border" },
  session_recap: { label: "Recap", cls: "text-muted border-border" },
};

function fmtTime(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function DraftCard({
  draft,
  busy,
  onApprove,
  onReject,
  onSaveEdit,
}: {
  draft: AIDraftView;
  busy: boolean;
  onApprove: (id: string) => void;
  onReject: (id: string) => void;
  onSaveEdit: (id: string, rawText: string) => void;
}) {
  const [editOpen, setEditOpen] = useState(false);
  const [draftText, setDraftText] = useState(draft.rawText);
  const [confirmReject, setConfirmReject] = useState(false);
  const [revealSecret, setRevealSecret] = useState(false);

  const meta = ENTITY_META[draft.entityType];
  const isRejected = draft.status === "rejected";
  const isApproved = draft.status === "approved";
  const locked = isRejected || isApproved;

  return (
    <li
      className={`rounded-lg border bg-surface p-4 ${
        isRejected ? "border-border opacity-50" : "border-border"
      }`}
    >
      {/* Header: badges + timestamp */}
      <div className="flex items-center gap-2 mb-2">
        <span className={`text-xs rounded-full px-2 py-0.5 border ${meta.cls}`}>{meta.label}</span>
        <span
          className={`text-xs rounded-full px-2 py-0.5 border ${
            draft.provider === "ollama" ? "text-arcane border-arcane/40" : "text-muted border-border"
          }`}
          title={draft.provider === "ollama" ? "Generated by Ollama" : "Imported (paste)"}
        >
          {draft.provider === "ollama" ? "Ollama" : "Import"}
        </span>
        {isApproved && (
          <span className="text-xs rounded-full px-2 py-0.5 border text-success border-success/40">
            ✓ Approved
          </span>
        )}
        <span className="ml-auto text-xs text-faint tnum">{fmtTime(draft.createdAt)}</span>
      </div>

      {/* Prompt */}
      {draft.prompt !== "(imported)" && (
        <p className="text-sm text-muted line-clamp-1 mb-2" title={draft.prompt}>
          Prompt: {draft.prompt}
        </p>
      )}

      <div className="border-t border-border my-2" />

      {/* Parsed preview */}
      <ParsedPreview
        draft={draft}
        revealSecret={revealSecret}
        onToggleSecret={() => setRevealSecret((v) => !v)}
      />

      {/* Edit accordion + actions */}
      {!locked && (
        <>
          <button
            onClick={() => setEditOpen((v) => !v)}
            className="mt-3 inline-flex items-center gap-1 text-xs text-muted hover:text-text"
            aria-expanded={editOpen}
          >
            {editOpen ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
            Edit raw text
          </button>

          {editOpen && (
            <div className="mt-2">
              <textarea
                value={draftText}
                onChange={(e) => setDraftText(e.target.value)}
                rows={6}
                className="w-full rounded-md bg-bg border border-border px-3 py-2 text-sm font-mono"
                aria-label="Edit raw draft text"
              />
              <button
                onClick={() => onSaveEdit(draft.id, draftText)}
                disabled={busy || draftText.trim() === draft.rawText.trim()}
                className="mt-2 rounded-md border border-border px-3 py-1.5 text-xs hover:bg-surface-raised disabled:opacity-40"
              >
                Save edits
              </button>
            </div>
          )}

          <div className="mt-3 flex items-center justify-end gap-2">
            {confirmReject ? (
              <span className="flex items-center gap-2 text-xs">
                <span className="text-muted">Reject this draft?</span>
                <button
                  onClick={() => {
                    onReject(draft.id);
                    setConfirmReject(false);
                  }}
                  disabled={busy}
                  className="rounded-md border border-danger/50 text-danger px-3 py-1.5 hover:bg-danger/10"
                >
                  Reject
                </button>
                <button
                  onClick={() => setConfirmReject(false)}
                  className="rounded-md border border-border px-3 py-1.5 hover:bg-surface-raised"
                >
                  Cancel
                </button>
              </span>
            ) : (
              <button
                onClick={() => setConfirmReject(true)}
                disabled={busy}
                className="rounded-md border border-danger/50 text-danger px-3 py-1.5 text-xs hover:bg-danger/10 disabled:opacity-40"
              >
                Reject
              </button>
            )}
            <button
              onClick={() => onApprove(draft.id)}
              disabled={busy}
              className="inline-flex items-center gap-1 rounded-md border border-accent text-accent px-3 py-1.5 text-xs font-semibold hover:bg-accent/10 disabled:opacity-40"
            >
              <Check className="w-3.5 h-3.5" aria-hidden /> Approve
            </button>
          </div>
        </>
      )}
    </li>
  );
}

// ── Parsed content preview per entity type ──────────────────────────────────
function ParsedPreview({
  draft,
  revealSecret,
  onToggleSecret,
}: {
  draft: AIDraftView;
  revealSecret: boolean;
  onToggleSecret: () => void;
}) {
  const p = draft.parsedJson as Record<string, unknown> | null;

  if (p == null) {
    return (
      <p className="text-sm text-warning">
        Could not parse — edit the raw text below, then approve.
      </p>
    );
  }

  if (draft.entityType === "npc") {
    return (
      <div className="text-sm space-y-1">
        <p className="font-semibold text-text">{String(p.name ?? "Unnamed NPC")}</p>
        {p.role ? <p className="text-muted">{String(p.role)}</p> : null}
        {p.appearance ? <p className="text-muted line-clamp-2">{String(p.appearance)}</p> : null}
        {p.secret ? (
          <p className="text-muted">
            <button
              onClick={onToggleSecret}
              className="inline-flex items-center gap-1 text-xs text-faint hover:text-text"
            >
              {revealSecret ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
              {revealSecret ? "Hide secret" : "Show secret (DM)"}
            </button>
            {revealSecret && <span className="block mt-1 italic">{String(p.secret)}</span>}
          </p>
        ) : null}
      </div>
    );
  }

  if (draft.entityType === "loot") {
    const items = Array.isArray(p.items) ? (p.items as Array<Record<string, unknown>>) : [];
    return (
      <div className="text-sm space-y-1">
        <p className="text-muted tnum">
          CR {String(p.cr ?? "?")} · {String(p.xp ?? 0)} XP
        </p>
        <ul className="space-y-0.5">
          {items.map((it, i) => (
            <li key={i} className="text-muted">
              • <span className="text-text">{String(it.name)}</span>{" "}
              <span className="text-faint text-xs">({String(it.rarity)})</span>
            </li>
          ))}
        </ul>
      </div>
    );
  }

  if (draft.entityType === "quest") {
    const objectives = Array.isArray(p.objectives) ? (p.objectives as unknown[]) : [];
    return (
      <div className="text-sm space-y-1">
        <p className="font-semibold text-text">{String(p.name ?? "Untitled Quest")}</p>
        {p.giverHint ? <p className="text-muted text-xs">Giver: {String(p.giverHint)}</p> : null}
        <ul className="space-y-0.5 mt-1">
          {objectives.slice(0, 4).map((o, i) => (
            <li key={i} className="text-muted">
              ☐ {String(o)}
            </li>
          ))}
        </ul>
      </div>
    );
  }

  // session_recap
  const recap = typeof p.recap === "string" ? p.recap : draft.rawText;
  return <p className="text-sm text-muted line-clamp-4 whitespace-pre-wrap">{recap}</p>;
}
